apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-volume
  template:
    metadata:
      labels:
        app: web-volume
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: app-config
