replicaCount: 3

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hostname: app.localtest.me
  path: /

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
